stages:
    - build
    - test-skip
    - package
    - deploy

variables:
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
    DOCKER_IMAGE_TAGGED: helmholtzcloud/cerebrum:$CI_COMMIT_SHA
    DOCKER_IMAGE_LATEST: helmholtzcloud/cerebrum:latest

cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
        - .m2/repository
        - target/

include:
    - local: .gitlab/ci/ci.yml
