cerebrum:
  test:
    oauth2-token: ${token:notoken}
  version: @project.version@
  allowed:
      origins: https://localhost:8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.boot.autoconfigure: DEBUG

server:
  port: 8090
  forward-headers-strategy: NATIVE
  error:
    whitelabel:
      enabled: false

spring:
  data:
    rest:
      base-path: /api/v0
    neo4j:
      username: neo4j
      password: secret
  mvc:
    throw-exception-if-no-handler-found: true
  profiles:
    active: @activatedProperties@
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.helmholtz.de/oauth2
          jwk-set-uri: https://login.helmholtz.de/oauth2/jwk

springdoc:
  api-docs:
    path: ${spring.data.rest.base-path}/cerebrum-docs
  swagger-ui:
    path: /
    operations-sorter: method
    oauth:
      client-id: helmholtz-marketplace-implicit
      client-secret: ${clientSecret}
      use-basic-authentication-with-access-code-grant: true