cerebrum:
  test:
    oauth2-token: ${token:notoken}
  version: @project.version@
  allowed:
      origins: https://localhost:8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.data.neo4j.cypher: TRACE
    org.springframework.boot.autoconfigure: DEBUG
    org.neo4j.driver.GraphDatabase: TRACE
    org.neo4j.driver.Driver: TRACE
    org.neo4j.driver.OutboundMessageHandler: TRACE
    org.neo4j.driver.InboundMessageDispatcher: TRACE

server:
  port: 8090
  forward-headers-strategy: NATIVE
  error:
    whitelabel:
      enabled: false

org:
  neo4j:
    driver:
      uri: bolt://localhost:7687
      authentication:
        username: neo4j
        password: test

spring:
  data:
    rest:
      base-path: /api/v0
  mvc:
    throw-exception-if-no-handler-found: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.helmholtz.de/oauth2
          jwk-set-uri: https://login.helmholtz.de/oauth2/jwk

springdoc:
  api-docs:
    path: ${spring.data.rest.base-path}/cerebrum-docs
  swagger-ui:
    path: /
    operations-sorter: method
    oauth:
      client-id: helmholtz-marketplace-implicit
      client-secret: ${clientSecret}
      use-basic-authentication-with-access-code-grant: true
