cerebrum:
  test:
    oauth2-token: ${token:notoken}
  version: @project.version@
  allowed:
      origins: http://localhost:8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
    org.springframework.data.mongodb: TRACE

server:
  port: 8090
  forward-headers-strategy: NATIVE
  error:
    whitelabel:
      enabled: false
  shutdown: "graceful"

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info,metric,shutdown"
  metrics:
    tags:
      application: ${spring.application.name}

spring:
  application:
    name: cerebrum-app
  data:
    rest:
      base-path: /api/v0
  mvc:
    throw-exception-if-no-handler-found: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.helmholtz.de/oauth2
          jwk-set-uri: https://login.helmholtz.de/oauth2/jwk

springdoc:
  api-docs:
    path: ${spring.data.rest.base-path}/cerebrum-docs
  swagger-ui:
    path: /
    operations-sorter: method
    oauth:
      client-id: helmholtz-marketplace-implicit
      client-secret: ${clientSecret}
      use-basic-authentication-with-access-code-grant: true
