cerebrum:
  allowed:
    client:
      origins:
        - https://localhost
        - http://localhost:8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.boot.autoconfigure: DEBUG

server:
  port: 8090
  forward-headers-strategy: NATIVE

spring:
  data:
    rest:
      base-path: /api/v0
    neo4j:
      username: neo4j
      password: secret
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.helmholtz-data-federation.de/oauth2
          jwk-set-uri: https://login.helmholtz-data-federation.de/oauth2/jwk